controller_manager:
  ros__parameters:
    update_rate: 50

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    publish_rate: 50
    base_frame_id: base_link
    left_wheel_names:  ["joint_rear_left_wheel"]
    right_wheel_names: ["joint_rear_right_wheel"]
    wheel_separation: 0.5
    wheel_radius: 0.15
    cmd_vel_timeout: 0.25
    use_stamped_vel: false
